name: lab9
channels:
    - conda-forge
    - defaults
dependencies:
    - matplotlib    # 2D plotting library
    - pandas        # Labelled table data
    - numpy         # N-d array and numerics 
    - jupyter       # Interactive notebooks
    - folium        # Python wrapper for Leaflet.js for plotting interactive maps
