name: lab1
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.8    # Python version 3.8
    - matplotlib    # 2D plotting library
    - numpy         # N-d array and numerics 
    - pandas        # Labeled data analysis
    - jupyter       # Interactive notebooks
